# This file contains values from Cookiecutter

default_context:
  project_name: "langchaing-nl2sql"
  project_description: "Langchaing tabular data query POC"
  organization: "SageData"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "dimitar-petrunov-sagedata"
  email: "dimitar.petrunov@sagedata.net"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
